variables:
  IMAGE_TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

stages:
  - build
  - push
  - deploy


maven-build:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: push
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - |
      for i in $(seq 1 30); do
        docker info && break
        echo "Waiting for docker daemon..."
        sleep 1
      done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

deploy-to-k8s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config
  script:
    - sed -i "s|__IMAGE__|$CI_REGISTRY_IMAGE:$IMAGE_TAG|g" k8s/deployment.yaml
    - kubectl -n default apply -f k8s/

