variables:
  IMAGE_TAG: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA

stages:
  - build
  - push


maven-build:
  stage: build
  image: maven:3.8.5-openjdk-8
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: push
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - |
      for i in $(seq 1 30); do
        docker info && break
        echo "Waiting for docker daemon..."
        sleep 1
      done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_SERVER_HOST
  script:
    - docker build -t "$CI_SERVER_HOST/$CI_PROJECT_PATH:$IMAGE_TAG" .
    - docker push "$CI_SERVER_HOST/$CI_PROJECT_PATH:$IMAGE_TAG"

